### ISSUE TITLE
A support for 8080-I interface?

### ISSUE THREAD

**Issue by vitasam** [abhra0897/stm32f1_ili9341_parallel#1]

**Comment by vitasam** [comment]
Hi, nice driver for libopencm3!
Would it be possible to add a support for 8080-I interface?

**Comment by abhra0897** [comment]
@vitasam 8080-I is not that different from 8080-II. Only thing that changes is which set of pins of the display to be used. For 8080-I, it's LSB aligned (D0-D7). For 8080-II, it's MSB aligned (D8-D15).

So, just follow the wiring [here](https://github.com/abhra0897/stm32f1_ili9341_parallel#wiring) and use those display pins with your mcu. The code remains the same.

**Comment by vitasam** [comment]
Thanks! I think that I was a little misled by the fact that you have specified the project as for 8080-II bus. 

By the way, is 8080-II bus located at D10-D17 (not D8-D15) ?

**Comment by abhra0897** [comment]
> you have specified the project as for 8080-II bus.

Actually, I mentioned 8080-II because I used a 8080-II display. I'll update the readme soon. :)

> By the way, is 8080-II bus located at D10-D17 (not D8-D15) ?

Oops, yes you're right.. My bad.

**Comment by vitasam** [comment]
Ok thanks! I think I will close this issue, not needed :)

**Comment by vitasam** [comment]
Resolved
