### ISSUE TITLE
ILI9341 simulator

### ISSUE THREAD

**Issue by vitasam** [abhra0897/stm32f1_ili9341_parallel#4]
Hello, I just found this ILI9341 simulator for Visual Studio, maybe you will be interesting to try:
https://github.com/LaBlazer/lcd-simulator

I copy/pasted part of your code, it seems to work as expected:
![image](https://user-images.githubusercontent.com/5597505/92325016-d41d6400-f04f-11ea-9e1e-15860b951653.png)

**Comment by abhra0897** [comment]
Great! Seems really interesting. Unfortunately, it says `"Currently works only on x64 Windows"` but I'm on GNU/Linux. 😑

**Comment by abhra0897** [comment]
Btw, I made something similar while working on my UI library project., That one is still under development.

![IMG_20200505_030724](https://user-images.githubusercontent.com/17234315/92329681-a9023700-f086-11ea-995d-c435a8652461.jpg)

**Comment by vitasam** [comment]
Yes, "windows only" is the only reason I did not fork that project yet :)

Your project looks very promising!
