### ISSUE TITLE
void ili_draw_char(uint16_t x, uint16_t y, char c, uint16_t color, const tFont* font)

### ISSUE THREAD

**Issue by vitasam** [abhra0897/stm32f1_ili9341_parallel#5]
Hello,
what about adding char-based function, e.g.:
`void ili_draw_char(uint16_t x, uint16_t y, char c, uint16_t color, const tFont* font)`

In many situation (e.g. in my stm32basic project) there is a need to draw info char by char, rather then by the whole string

**Comment by vitasam** [comment]
Another question in to the same issue: every time when a new character from the string should be displayed, there is a `for() loop` through the whole font structure array:

```
...
for (uint8_t i = 0; i < font->length; i++)
{
    if (font->chars[i].code == *str)
    {
...
    }
}
```

Why is it so - due to unicode support? Typically the font array is made in such a way where the ASCII code is an index of the array (talking about non-unicode fonts)

**Comment by abhra0897** [comment]
> Hello,
> what about adding char-based function, e.g.:
> `void ili_draw_char(uint16_t x, uint16_t y, char c, uint16_t color, const tFont* font)`
> 
> In many situation (e.g. in my stm32basic project) there is a need to draw info char by char, rather then by the whole string

There is already a character drawing function. The string drawing function calls this one:
https://github.com/abhra0897/stm32f1_ili9341_parallel/blob/39259d822eed40b2831bbc31ef9e30aa6373300a/ili9341_stm32_parallel8.c#L68



> Another question in to the same issue: every time when a new character from the string should be displayed, there is a `for() loop` through the whole font structure array:
> 
> ```
> ...
> for (uint8_t i = 0; i < font->length; i++)
> {
>     if (font->chars[i].code == *str)
>     {
> ...
>     }
> }
> ```
> 
> Why is it so - due to unicode support? Typically the font array is made in such a way where the ASCII code is an index of the array (talking about non-unicode fonts)

The character array looks like this:
```C
static const tChar Font_Microsoft_16_array[] = {
  // character: ' '
  {0x20, &Font_Microsoft_16_0x20},

  // character: '!'
  {0x21, &Font_Microsoft_16_0x21},

  // character: '\"'
  {0x22, &Font_Microsoft_16_0x22},

 /// More characters below ........... ///
}
```
So, array index starts from 0 but ascii character starts from 32 (0 - 31 are control characters). if we offset by 32, then it's possible to do like this: ```img = font->chars[*str - 32].image;```, but if any character is missing in the array (for custom made fonts), the output will be wrong. Relying solely on positional index works as long as you don't have any missing character. 

An example: if you remove  lower-case '**a**' characters when making a font, then doing ```img = font->chars['b' - 32].image;``` will not print **b**, rather it print **c** because **b** is now in **a**'s place and **c** is now in **b**'s place.
If you remove some unnecessary characters when making font, then this way of character searching **shall** cause problem.

Otherwise it's a great way to reduce size and increase speed.

**Comment by vitasam** [comment]
Hi,

> There is already a character drawing function. The string drawing function calls this one:
>  `void ili_draw_char(uint16_t x, uint16_t y, uint16_t fore_color, uint16_t back_color, const tImage *glyph, uint8_t is_bg) `

Yes, I know that, this supposed to be a kind of "private" function, since it takes a font image glyph, but not a `char` character. My question was to make a "public" function.

About font tables - I got your point. Still I'm thinking that since the whole project is targeting a quite limited embedded platforms (e.g. `stm32f103` or potentially even smaller ones) it will be wise to reduce the size (and increase speed). 

For example, I already got a linker error when was trying to build my [stm32basic](https://github.com/vitasam/stm32basic/tree/master/stmbasic_app) app with your TFT code - the size of binary exceeded f103's ROM size by 152 bytes :)

**Comment by abhra0897** [comment]
I'm working on adding a public draw_char function, wait a bit :)

Regarding the font table, I'm thinking about it. I sometimes use stripped-down fonts to keep my code small. So, if I change the searching method to the one proposed by you, I can't use it anymore. 

Maybe I can add another function?

**Comment by vitasam** [comment]
> I'm working on adding a public draw_char function, wait a bit :)

Great!

> Maybe I can add another function?

Yes, exactly! This function will be useful for those users who know that they have a complete font array and don't want to remove any character from there

**Comment by abhra0897** [comment]
Added character drawing function. 
https://github.com/abhra0897/stm32f1_ili9341_parallel/blob/861cd0e5aeafc5067c741f4cc1fea44b32656fa6/ili9341_stm32_parallel8.c#L220

![IMG_20200907_124648](https://user-images.githubusercontent.com/17234315/92359139-62552100-f108-11ea-95a8-ae6b91676173.jpg)

**Comment by vitasam** [comment]
Looks very good, exactly what I needed now! So I will reset my fork to your upstream now.

Meanwhile I've been playing with LCD-font converter, this `Fixedsys` monospace font seems to be looking authentically for `stm32basic` purpose:
![image](https://user-images.githubusercontent.com/5597505/92359990-c66dea00-f0f4-11ea-8160-ae1337c4a990.png)

**Comment by abhra0897** [comment]
Looks nice! I added fixedsys font in my fonts_embedded repo.

**Comment by vitasam** [comment]
Thanks! Now everything seems to be Ok, I will close the issue
