### ISSUE TITLE
Write a character on top of previously written character 

### ISSUE THREAD

**Issue by vitasam** [abhra0897/stm32f1_ili9341_parallel#6]
Hi, 
what happens when a character goes on top of previously written character? 

Assuming monospace front, it will be the same rectangle - should one take care about cleaning the rectangle manually or the driver takes care about it?

**Comment by abhra0897** [comment]
If you set "is_bg = 1", then the new character will "clean" the old character and only the new character will be shown.
If "is_bg = 0", that means the character is transparent. So, the old character can be seen through the new character. Of course it will make it unreadable.

*is_bg defines if the glyph will be drawn with background (solid glyph) or without background (transparent glyph)

**Comment by vitasam** [comment]
Thanks for the info, I will test it
