### ISSUE TITLE
CS_ACTIVE is commented out

### ISSUE THREAD

**Issue by vitasam** [abhra0897/stm32f1_ili9341_parallel#7]
Hi,

just noticed that CS_ACTIVE is commented out - what is a reason?

```
__attribute__((always_inline)) static inline void _ili_write_command_8bit(uint8_t cmd)
{
	//CS_ACTIVE;
	ILI_DC_CMD;
	ILI_WRITE_8BIT(cmd);
}
```

**Comment by abhra0897** [comment]
As per ILI9341 datasheet, the CS pin can be always set to low. So, in my driver CS pin is set to low (`ILI_CS_ACTIVE`) in the display initialization routine (`ili_init()`). Releasing and selecting the display every time will make the overall performance slightly slower.
So, I decided to select the display once at the beginning and don't unselect/re-select it ever. It made it run faster.

But, I'll soon modify the code to make this optional like my st7789 code. Users may decide whether to always select the display or to release it when not used.

**Comment by vitasam** [comment]
Ok, thanks!
